version: "3.7"

services:
    base_station:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "1146/udp"
            - "1145/udp"
    # node1:
    #     dockerfile: Dockerfile
    #     ports:
    #         - "1146/udp"
    #         - "1145/udp"
