version: "3.7"

services:
    multicaster:
        build:
            context: "local-multicast/."
            dockerfile: Dockerfile
        ports:
            - "1100/udp"
        environment:
            - MULTICASTER_PORT=1100
    base_station:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "1140/udp"
            - "1146/udp"
        environment:
            - NODENAME=basestation
            - ANNOUNCEMULTICAST=false
            - ANNOUNCEADDR=multicaster:1100
            - ANNOUNCELISTENPORT=1140
            - DATALISTENPORT=1146
            - PROFILEPATH=./profiles/base_station/
        volumes:
            - "./:/app/"
        init: true
    node1:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "1140/udp"
            - "1147/udp"
        environment:
            - NODENAME=node1
            - ANNOUNCEMULTICAST=false
            - ANNOUNCEADDR=multicaster:1100
            - ANNOUNCELISTENPORT=1140
            - DATALISTENPORT=1147
            - PROFILEPATH=./profiles/node1/
        volumes:
            - "./:/app/"
        init: true
