version: "3.7"

services:
    base_station:
        image: alpine:latest
        ports:
            - target: 5311
              protocol: udp
              mode: host

    node1:
        image: alpine:latest
        ports:
            - target: 5311
              protocol: udp
              mode: host
