version: "3.7"

services:
    # multicaster:
    #     build:
    #         context: "local-multicast/."
    #         dockerfile: Dockerfile
    #     ports:
    #         - "1140/udp"
    #     environment:
    #         - MULTICASTER_PORT=1140
    base_station:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "1140:1140/udp"
            - "1146/udp"
        environment:
            - NODENAME=basestation
            - ANNOUNCEMULTICAST=false
            - ANNOUNCEADDR=host.docker.internal:1140
            - ANNOUNCELISTENPORT=1140
            - DATALISTENPORT=1146
        volumes:
            - "./:/app/"
        init: true
    # node1:
    #     build:
    #         context: .
    #         dockerfile: Dockerfile
    #     ports:
    #         - "1140/udp"
    #         - "1147/udp"
    #     environment:
    #         - NODENAME=node1
    #         - ANNOUNCEMULTICAST=false
    #         - ANNOUNCEADDR=multicaster:1140
    #         - ANNOUNCELISTENPORT=1140
    #         - DATALISTENPORT=1147
